In [76]:
import pickle

data = []

with open(f"traces_1_runs_5_sec_win32_OS_full_asVar.pkl", 'rb') as f:
    data = pickle.load(f)

In [77]:
for i in range(len(data)):
    data[i][3] = data[i][3].name

In [78]:
import pandas
data_points = pandas.DataFrame()

for row in data:
    trace = row[0]
    codec, browser, player, platform, user, timestamp = row[1:]
    new_data_point = pandas.DataFrame(data=[[*trace, codec, browser, player, platform, user, timestamp]], columns=[*range(1,len(trace)+1), "codec", "browser", "player", "platform", "user", "timestamp"])
    data_points = pandas.concat((data_points, new_data_point))

In [46]:
data_points.loc[data_points["browser"].apply(lambda x: x in ["CHROME", "FIREFOX"])]

1      2      3      4      5      6      7      8      9     10  ...  \
0      0  19716  19716  19716  19716  19716  26598  26598  26598  26598  ...   
0  23137  23137  23137  23137  23137  23478  23478  23478  23478  23478  ...   
0  19799  19799  19799  19799  19799  24594  24594  24594  24594  24594  ...   
0   3698   3698   3698   3698   3698   3705   3705   3705   3705   3705  ...   
0   6957   6957   6957   6957   6957   7269   7269   7269   7269   7269  ...   
0   6957   6957   6957   6957   6957   7045   7045   7045   7045   7045  ...   
0  19306  19306  19306  19306  19306  29653  29653  29653  29653  29653  ...   
0  17982  17982  17982  17982  17982  32187  32187  32187  32187  32187  ...   
0  19259  19259  19259  19259  19259  25546  25546  25546  25546  25546  ...   
0   6704   6704   6704   6704   6704   7020   7020   7020   7020   7020  ...   
0   6273   6273   6273   6273   6273   5258   5258   5258   5258   5258  ...   
0   6910   6910   6910   6910   6910   6773   6773   6773   6773   6773  ...   
0  16013  16013  16013  16013  16013  32853  32853  32853  32853  32853  ...   
0      0  24285  24285  24285  24285  24285  27458  27458  27458  27458  ...   
0  27162  27162  27162  27162  27162  23078  23078  23078  23078  23078  ...   
0   6087   6087   6087   6087   6087   6269   6269   6269   6269   6269  ...   
0   4603   4603   4603   4603   4603   6288   6288   6288   6288   6288  ...   
0   7176   7176   7176   7176   7176   7875   7875   7875   7875   7875  ...   
0  11768  11768  11768  11768  11768  25168  25168  25168  25168  25168  ...   
0  14388  14388  14388  14388  14388  32035  32035  32035  32035  32035  ...   
0      0  17068  17068  17068  17068  17068  22762  22762  22762  22762  ...   
0   6917   6917   6917   6917   6917   4600   4600   4600   4600   4600  ...   
0   6470   6470   6470   6470   6470   6361   6361   6361   6361   6361  ...   
0   6957   6957   6957   6957   6957   6900   6900   6900   6900   6900  ...   

    4997   4998   4999   5000       codec  browser                    player  \
0  31334  31334  31334  31334  sample.mp4  FIREFOX      SupportedPlayers.MPV   
0  36255  36255  36255  36255  sample.mp4  FIREFOX  SupportedPlayers.MPLAYER   
0  34297  34297  34297  34297  sample.mp4  FIREFOX      SupportedPlayers.VLC   
0   9208   9208   9208   9208  sample.mp4   CHROME      SupportedPlayers.MPV   
0   9352   9352   9352   9352  sample.mp4   CHROME  SupportedPlayers.MPLAYER   
0   9397   9397   9397   9397  sample.mp4   CHROME      SupportedPlayers.VLC   
0  36556  36556  36556  36556  sample.flv  FIREFOX      SupportedPlayers.MPV   
0  30435  30435  30435  30435  sample.flv  FIREFOX  SupportedPlayers.MPLAYER   
0  41690  41690  41690  41690  sample.flv  FIREFOX      SupportedPlayers.VLC   
0   7678   7678   7678   7678  sample.flv   CHROME      SupportedPlayers.MPV   
0   9637   9637   9637   9637  sample.flv   CHROME  SupportedPlayers.MPLAYER   
0   9392   9392   9392   9392  sample.flv   CHROME      SupportedPlayers.VLC   
0  37645  37645  37645  37645  sample.3gp  FIREFOX      SupportedPlayers.MPV   
0  43710  43710  43710  43710  sample.3gp  FIREFOX  SupportedPlayers.MPLAYER   
0  27005  27005  27005  27005  sample.3gp  FIREFOX      SupportedPlayers.VLC   
0   9257   9257   9257   9257  sample.3gp   CHROME      SupportedPlayers.MPV   
0   9477   9477   9477   9477  sample.3gp   CHROME  SupportedPlayers.MPLAYER   
0   9169   9169   9169   9169  sample.3gp   CHROME      SupportedPlayers.VLC   
0  36741  36741  36741  36741  sample.mkv  FIREFOX      SupportedPlayers.MPV   
0  34650  34650  34650  34650  sample.mkv  FIREFOX  SupportedPlayers.MPLAYER   
0  29445  29445  29445  29445  sample.mkv  FIREFOX      SupportedPlayers.VLC   
0   7985   7985   7985   7985  sample.mkv   CHROME      SupportedPlayers.MPV   
0   5090   5090   5090   5090  sample.mkv   CHROME  SupportedPlayers.MPLAYER   
0   9474   9474   9474   9474  sample.mkv   CHROME      SupportedPlayers.VLC   

   pl

In [49]:
import numpy as np

In [79]:

combinations = np.meshgrid(["FIREFOX"], data_points["codec"].unique(), data_points["player"].unique())
combinations = np.array(combinations).T.reshape(-1, 3)
print(combinations)

[['FIREFOX' 'sample.mp4' 'MPV']
 ['FIREFOX' 'sample.flv' 'MPV']
 ['FIREFOX' 'sample.3gp' 'MPV']
 ['FIREFOX' 'sample.mkv' 'MPV']
 ['FIREFOX' 'sample.mp4' 'MPLAYER']
 ['FIREFOX' 'sample.flv' 'MPLAYER']
 ['FIREFOX' 'sample.3gp' 'MPLAYER']
 ['FIREFOX' 'sample.mkv' 'MPLAYER']
 ['FIREFOX' 'sample.mp4' 'VLC']
 ['FIREFOX' 'sample.flv' 'VLC']
 ['FIREFOX' 'sample.3gp' 'VLC']
 ['FIREFOX' 'sample.mkv' 'VLC']]


In [82]:
from sklearn.preprocessing import LabelEncoder

# create a label encoder object
le = LabelEncoder()
df = data_points
# fit the label encoder to your pandas column
df['browser'] = le.fit_transform(df['browser'])
print(df["browser"].unique())

[2 0 1]


In [84]:
df[df["player"] == "MPV"]

1      2      3      4      5      6      7      8      9     10  ...  \
0      0  19716  19716  19716  19716  19716  26598  26598  26598  26598  ...   
0   3698   3698   3698   3698   3698   3705   3705   3705   3705   3705  ...   
0   5169   5169   5169   5169   5169   6987   6987   6987   6987   6987  ...   
0  19306  19306  19306  19306  19306  29653  29653  29653  29653  29653  ...   
0   6704   6704   6704   6704   6704   7020   7020   7020   7020   7020  ...   
0   6957   6957   6957   6957   6957   7151   7151   7151   7151   7151  ...   
0  16013  16013  16013  16013  16013  32853  32853  32853  32853  32853  ...   
0   6087   6087   6087   6087   6087   6269   6269   6269   6269   6269  ...   
0   7291   7291   7291   7291   7291   7996   7996   7996   7996   7996  ...   
0  11768  11768  11768  11768  11768  25168  25168  25168  25168  25168  ...   
0   6917   6917   6917   6917   6917   4600   4600   4600   4600   4600  ...   
0   3953   3953   3953   3953   3953   3847   3847   3847   3847   3847  ...   

    4997   4998   4999   5000       codec  browser  player  platform  \
0  31334  31334  31334  31334  sample.mp4        2     MPV     win32   
0   9208   9208   9208   9208  sample.mp4        0     MPV     win32   
0   9854   9854   9854   9854  sample.mp4        1     MPV     win32   
0  36556  36556  36556  36556  sample.flv        2     MPV     win32   
0   7678   7678   7678   7678  sample.flv        0     MPV     win32   
0   8718   8718   8718   8718  sample.flv        1     MPV     win32   
0  37645  37645  37645  37645  sample.3gp        2     MPV     win32   
0   9257   9257   9257   9257  sample.3gp        0     MPV     win32   
0  10070  10070  10070  10070  sample.3gp        1     MPV     win32   
0  36741  36741  36741  36741  sample.mkv        2     MPV     win32   
0   7985   7985   7985   7985  sample.mkv        0     MPV     win32   
0   9203   9203   9203   9203  sample.mkv        1     MPV     win32   

           user   timestamp  
0  ali.parlakci  1672857211  
0  ali.parlakci  1672857274  
0  ali.parlakci  1672857315  
0  ali.parlakci  1672857388  
0  ali.parlakci  1672857650  
0  ali.parlakci  1672857691  
0  ali.parlakci  1672857798  
0  ali.parlakci  1672857864  
0  ali.parlakci  1672857904  
0  ali.parlakci  1672857992  
0  ali.parlakci  1672858084  
0  ali.parlakci  1672858126  

[12 rows x 5006 columns]

In [5]:
import pandas

class Warehouse:
    def __init__(self):
        self.trace_len = -1 
        self.data_points = None
        self.raw_data_points = []

    def insert(self, row):
        self._validate_trace(row[0])

        trace = row[0]
        codec, browser, player, platform, user, timestamp = row[1:]
        new_data_point = [*trace, codec, browser, player.name, platform, user, timestamp]
        self.raw_data_points.append(new_data_point)

    def get_df(self):
        if self.data_points is None:
            self.convert_to_df()
        return self.data_points

    def convert_to_df(self):
        self.data_points = pandas.DataFrame(data=self.raw_data_points, columns=[*[f"{feature}" for feature in range(1,len(self.raw_data_points[0])-6+1)], "codec", "browser", "player", "platform", "user", "timestamp"])
        return self.data_points

    def _validate_trace(self, trace):
        if self.trace_len == -1:
            self.trace_len = len(trace)
        else:
            if self.trace_len != len(trace):
                raise Exception()

In [25]:
from tqdm import tqdm
import os
import pickle

warehouse = Warehouse()

for root, _, files in os.walk("./partitioned_results/linux_umut/"):
    for file in tqdm(files):
        file_path = os.path.join(root, file)
        with open(file_path, 'rb') as f:
            data = pickle.load(f)
            for row in data:
                warehouse.insert(row)

df = warehouse.get_df()

100%|██████████| 36/36 [00:02<00:00, 13.91it/s]


In [26]:
df

1      2      3      4      5      6      7      8      9     10  \
0     48821  48821  48821  48821  48821  37042  37042  37042  37042  37042   
1     31853  31853  31853  31853  31853  34434  34434  34434  34434  34434   
2     54374  54374  54374  54374  54374  47318  47318  47318  47318  47318   
3      6676   6676   6676   6676   6676   2014   2014   2014   2014   2014   
4      8033   8033   8033   8033   8033   7786   7786   7786   7786   7786   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3595   8092   8092   8092   8092   8092   9478   9478   9478   9478   9478   
3596   5553   5553   5553   5553   5553   5294   5294   5294   5294   5294   
3597   5673   5673   5673   5673   5673   5166   5166   5166   5166   5166   
3598   5640   5640   5640   5640   5640   5449   5449   5449   5449   5449   
3599  29482  29482  29482  29482  29482  38634  38634  38634  38634  38634   

      ...  14997  14998  14999  15000       codec  browser   player  \
0     ...  67674  67674  67674  67674  sample.mp4  FIREFOX      MPV   
1     ...  72455  72455  72455  72455  sample.mp4  FIREFOX  MPLAYER   
2     ...  66090  66090  66090  66090  sample.mp4  FIREFOX      VLC   
3     ...  16298  16298  16298  16298  sample.mp4   CHROME      MPV   
4     ...  16781  16781  16781  16781  sample.mp4   CHROME  MPLAYER   
...   ...    ...    ...    ...    ...         ...      ...      ...   
3595  ...  15158  15158  15158  15158  sample.3gp   CHROME      VLC   
3596  ...  14635  14635  14635  14635  sample.3gp     EDGE      MPV   
3597  ...  14684  14684  14684  14684  sample.3gp     EDGE  MPLAYER   
3598  ...  11242  11242  11242  11242  sample.3gp     EDGE      VLC   
3599  ...  61718  61718  61718  61718  sample.mkv  FIREFOX      MPV   

                                           platform  user   timestamp  
0     Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672939828  
1     Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672939846  
2     Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672939864  
3     Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672939880  
4     Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672939896  
...                                             ...   ...         ...  
3595  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956412  
3596  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956428  
3597  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956444  
3598  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956460  
3599  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956478  

[3600 rows x 15006 columns]

In [27]:
test_df = df.loc[:]
test_df = test_df[test_df["browser"] == "FIREFOX"]
test_df = test_df[test_df["player"] == "VLC"]
test_df

1      2      3      4      5      6      7      8      9     10  \
2     54374  54374  54374  54374  54374  47318  47318  47318  47318  47318   
11    20729  20729  20729  20729  20729  28126  28126  28126  28126  28126   
20        0  35245  35245  35245  35245  35245  27917  27917  27917  27917   
29    37415  37415  37415  37415  37415  35081  35081  35081  35081  35081   
38    33609  33609  33609  33609  33609  52683  52683  52683  52683  52683   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3556  30403  30403  30403  30403  30403  45965  45965  45965  45965  45965   
3565  20621  20621  20621  20621  20621  47388  47388  47388  47388  47388   
3574  36876  36876  36876  36876  36876  36702  36702  36702  36702  36702   
3583  18225  18225  18225  18225  18225  28461  28461  28461  28461  28461   
3592  24378  24378  24378  24378  24378  28843  28843  28843  28843  28843   

      ...  14997  14998  14999  15000       codec  browser  player  \
2     ...  66090  66090  66090  66090  sample.mp4  FIREFOX     VLC   
11    ...  58641  58641  58641  58641  sample.flv  FIREFOX     VLC   
20    ...  68265  68265  68265  68265  sample.3gp  FIREFOX     VLC   
29    ...  64575  64575  64575  64575  sample.mkv  FIREFOX     VLC   
38    ...  63036  63036  63036  63036  sample.mp4  FIREFOX     VLC   
...   ...    ...    ...    ...    ...         ...      ...     ...   
3556  ...  60454  60454  60454  60454  sample.3gp  FIREFOX     VLC   
3565  ...  66187  66187  66187  66187  sample.mkv  FIREFOX     VLC   
3574  ...  62371  62371  62371  62371  sample.mp4  FIREFOX     VLC   
3583  ...  63936  63936  63936  63936  sample.flv  FIREFOX     VLC   
3592  ...  74651  74651  74651  74651  sample.3gp  FIREFOX     VLC   

                                           platform  user   timestamp  
2     Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672939864  
11    Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672940013  
20    Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672940163  
29    Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672940313  
38    Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672940463  
...                                             ...   ...         ...  
3556  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672955764  
3565  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672955914  
3574  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956064  
3583  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956214  
3592  Linux-5.15.0-56-generic-x86_64-with-glibc2.35  umut  1672956364  

[400 rows x 15006 columns]

In [44]:
data = []
with open("./test_results/different_codec/traces_100_runs_15_sec_linux_OS.pkl", "rb") as file:
    for traces, target in pickle.load(file):
        data.append([*traces, target])

test_df = pandas.DataFrame(data, columns=[*[f"{feature}" for feature in range(1,len(data[0]))], "target"])

In [45]:
y = np.array(test_df["target"])
X = np.array(test_df.drop(columns=["target"]))

In [51]:
le = LabelEncoder()
y = le.fit_transform(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,

In [28]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for column in ["browser", "player", "codec", "platform", "user"]:
    test_df[column] = le.fit_transform(test_df[column])

y = test_df["codec"]
X = test_df.drop(columns=["browser", "player", "codec", "platform", "user", "timestamp"])

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import top_k_accuracy_score
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_val_score

def _generate_model(X, y, test_size=0.2):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, stratify=y)
    
    clf = RandomForestClassifier()
    clf = clf.fit(X_train, y_train)
    print(X_train)
    print(y_train)
    y_probs = clf.predict_proba(X_test)
    top1 = top_k_accuracy_score(y_test, y_probs, k=1)

    return top1

In [55]:
import numpy as np

scores = []
for _ in tqdm(range(1)):
    scores.append(_generate_model(X, y))

print(f"{np.mean(scores):.2f}% (+/- {np.std(scores):.2f})")

100%|██████████| 1/1 [00:01<00:00,  1.47s/it]

[[ 5697  5697  5697 ... 16374 16374 16374]
 [ 7985  7985  7985 ... 16665 16665 16665]
 [ 8692  8692  8692 ... 16422 16422 16422]
 ...
 [11398 11398 11398 ... 17681 17681 17681]
 [ 7048  7048  7048 ... 16706 16706 16706]
 [ 8194  8194  8194 ... 13467 13467 13467]]
[0 3 1 3 0 0 0 3 1 1 2 0 2 0 1 1 1 1 0 2 3 1 0 0 0 0 0 3 1 2 3 1 1 3 3 0 3
 1 1 0 2 2 1 0 1 1 0 2 1 2 2 1 2 1 0 1 2 0 3 1 1 3 0 3 0 0 1 2 0 2 0 3 2 0
 0 2 2 3 0 0 2 2 1 0 2 2 2 3 3 0 2 0 3 3 0 2 0 2 1 3 0 3 1 3 1 0 3 1 2 0 1
 2 0 3 2 0 2 3 1 2 2 3 0 0 1 3 3 3 0 0 2 3 0 1 3 2 3 1 2 0 3 3 0 3 1 0 3 1
 3 2 0 1 2 1 1 3 3 2 2 0 0 0 3 0 0 3 3 2 2 2 0 0 2 1 2 0 3 0 1 3 2 1 0 2 2
 0 3 1 0 3 0 2 1 1 0 1 3 3 3 3 2 3 3 3 1 0 1 2 2 2 2 1 0 2 3 3 2 1 0 0 1 2
 2 3 1 0 0 1 2 2 2 0 2 3 1 2 0 0 1 0 3 0 3 1 2 3 3 3 1 2 2 3 0 2 3 1 2 0 2
 0 1 0 1 3 2 0 1 0 1 2 3 1 3 3 0 1 1 2 3 2 1 3 2 1 1 0 3 1 3 2 2 3 3 3 2 2
 1 2 2 3 2 3 3 3 1 1 1 1 2 3 1 1 1 1 3 0 1 1 2 1]
0.81% (+/- 0.00)
